[package]
name = "define"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1"
features = ["span-locations"]

[dependencies.syn]
version = "2"
default-features = false
features = ["parsing", "proc-macro"]
